In [11]:
# 切片与索引
'''
ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。
ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。
'''
# 示例 
import numpy as np

a = np.arange(10)
s = slice(2,7,2)  # 分别设置起始，终止和步长的参数为 2，7 和 2
print(a[s])   # [2 4 6]

# 通过冒号分隔切片参数 start:stop:step 来进行切片操作
b = a[2:7:2]    # 分别设置起始，终止和步长的参数为 2，7 和 2
print(b)   # [2 4 6]
c = a[2]   # 只取 2 这个参数
print(c)   # 2
d = a[2:]  # 从 2 开始以后的所有项都将被提取
print(d)   # [2 3 4 5 6 7 8 9]
e = a[2:5] # 提取两个索引(不包括停止索引)之间的项,即2到5之间但不包括5的数
print(e)   # [2 3 4]


# 多维数组同样适用上述索引提取方法
f = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(f)
print('从数组索引 f[1:] 处开始切割\n',f[1:])
'''
输出：
从数组索引 f[1:] 处开始切割
 [[3 4 5]
 [4 5 6]]
 
对二维数组，只写单个切片 f[m:] 是对行做切片
这里舍弃了第 0 行的数据，从第 1 行开始
若写成 f[:,1:]：逗号前管行，逗号后管列，代表所有行，从第 1 列开始截取
'''


[2 4 6]
[2 4 6]
2
[2 3 4 5 6 7 8 9]
[2 3 4]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
从数组索引 f[1:] 处开始切割
 [[3 4 5]
 [4 5 6]]


In [13]:
# 高级索引
'''
除了之前看到的用整数和切片的索引外，数组可以由整数数组索引、布尔索引及花式索引。
NumPy 中的高级索引指的是使用整数数组、布尔数组或者其他序列来访问数组的元素。
相比于基本索引，高级索引可以访问到数组中的任意元素，并且可以用来对数组进行复杂的操作和修改。
'''

# 整数数组索引
'''
用整数数组 / 整数列表作为下标，精准、不连续地取出数组任意位置元素，返回新数组，不是视图。
分为：一维数组整数索引、二维数组整数数组索引。

一维数组整数索引
语法
arr[ [i0, i1, i2,...] ]
列表里的数字是要提取的下标，顺序、重复都支持。

二维数组整数数组索引（重点）
二维 arr[行索引数组, 列索引数组]
规则：行、列两个整数数组长度必须相等，一一配对取 (行i,列j) 的元素。
'''
# 示例 1    一维数组整数索引
import numpy as np

a = np.array([10,20,30,40,50,60,70,80,90])
# 取下标0、4、8
idx = [0,4,8]    
b = a[idx]
print(b)      # [10 50 90]


# 示例 2    二维数组整数数组索引
# 输出为一维列表
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)
'''
输出：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
'''
row = [[0,0,3,3]]
col = [[0,2,0,2]]
y1 = x[row, col]
print(y1)   # [[ 0  2  9 11]]

# 输出为矩阵
rows = [[0,0],[3,3]]
cols = [[0,2],[0,2]]
y2 = x[rows, cols]
print(y2)
'''
输出：
[[ 0  2]
 [ 9 11]]

输出数字总数由索引元素数量决定
输出的维度 / 行列形状，完全跟着索引数组的形状走。
这里总共输出了4个数，索引组是2*2的矩阵，输出也就按这4个内容顺序分为2*2的矩阵
'''
# 切片 :
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = a[1:3, 1:3]
print(b)
'''
输出：
[[5 6]
 [8 9]]

a[行切片, 列切片]
1:3 是左闭右开，取下标 1、2
2. 行 1:3
取第 1 行 [4,5,6]、第 2 行 [7,8,9]
3. 列 1:3
每行只取下标 1、2 的元素：
第 1 行截取：5,6
第 2 行截取：8,9
'''

[10 50 90]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2  9 11]]
[[ 0  2]
 [ 9 11]]
[[5 6]
 [8 9]]


In [16]:
# 布尔索引
'''
用和原数组同形状的布尔数组（True/False）通过布尔运算（如：比较运算符） 筛选元素：
True：保留对应位置元素
False：丢弃对应位置元素
返回一维数组，存放所有满足条件的元素。
'''
# 获取大于 5 的元素

import numpy as np

x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]]) 
print (x)

mask = a > 5
print('布尔掩码 mask：\n',mask)
'''
输出：
布尔掩码 mask：
 [[False False False]
 [False False  True]
 [ True  True  True]]
'''
print(a[mask])   # [6 7 8 9]

# 从数组中过滤掉非复数元素。
a = np.array([1,2+6j,5,3.5+5j])
print(a[np.iscomplex(a)])   # [2. +6.j 3.5+5.j]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
布尔掩码 mask：
 [[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[2. +6.j 3.5+5.j]


In [25]:
# 花式索引
'''
花式索引指的是利用整数数组进行索引。
花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。
对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素，如果目标是二维数组，那么就是对应下标的行。
花式索引跟切片不一样，它总是将数据复制到新数组中。
'''

# 示例   一维数组
# 一维数组只有一个轴 axis = 0，所以一维数组就在 axis = 0 这个轴上取值

import numpy as np

x = np.arange(8,19)
print(x)  # [ 8  9 10 11 12 13 14 15 16 17 18]

print("-------读取下标对应的元素-------")

x2 = x[[0,6]]   # 使用花式索引,取第 0 位和第 6 位元素
print(x2)   # [ 8 14]
print(x2[0])   # 8
print(x2[1])   # 14


# 示例    二维数组
# 传入顺序索引数组

x = np.arange(32).reshape(8,4)
print(x)
'''
输出：              顺序序号      顺序序号      
[[ 0  1  2  3]        0            -1
 [ 4  5  6  7]        1            -2
 [ 8  9 10 11]        2            -3
 [12 13 14 15]        3            -4
 [16 17 18 19]        4            -5
 [20 21 22 23]        5            -6
 [24 25 26 27]        6            -7
 [28 29 30 31]]       7            -8
'''

print("-------读取下标对应的行-------")

x3 = x[[4,2,1,7]]   # 使用花式索引,输出下表行序号为 4, 2, 1, 7 对应的行
print(x3)
'''
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
'''


# 传入倒序索引数组
x=np.arange(32).reshape((8,4))
print (x[[-4,-2,-1,-7]])   # 逆序从 -1 开始往后
'''
输出：
[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]
'''

# 传入多个索引数组（要使用 np.ix_）
'''
np.ix_ 作用
np.ix_(行列表, 列列表)
把一维行索引、一维列索引广播成二维网格索引，取出所有行 × 列的交叉组合。

np.ix_ 函数就是输入两个数组，产生笛卡尔积的映射关系。
笛卡尔乘积是指在数学中，两个集合 X 和 Y 的笛卡尔积（Cartesian product），又称直积，表示为 X×Y;
第一个对象是X的成员而第二个对象是 Y 的所有可能有序对的其中一个成员。

例如 A={a,b}, B={0,1,2}，则：
A×B={(a, 0), (a, 1), (a, 2), (b, 0), (b, 1), (b, 2)}
B×A={(0, a), (0, b), (1, a), (1, b), (2, a), (2, b)}
'''

x=np.arange(32).reshape((8,4))
print (x[np.ix_([1,5,7,2],[0,3,1,2])])
'''
输出：
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]

行序列：[1,5,7,2] 4 行
列序列：[0,3,1,2] 4 列
先在取出 4 行的基础上，再取这 4 行每行的 0,3,1,2 ，并按顺序排列
最终取出 4×4 的矩阵，所有行和列两两配对。
'''

[ 8  9 10 11 12 13 14 15 16 17 18]
-------读取下标对应的元素-------
[ 8 14]
8
14
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
-------读取下标对应的行-------
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
