In [3]:
# 从数值范围创建数组

# numpy.arange
'''
numpy 包中的使用 arange 函数创建数值范围并返回 ndarray 对象，函数格式如下：

numpy.arange(start, stop, step, dtype)
根据 start 与 stop 指定的范围以及 step 设定的步长，生成一个 ndarray。
参数说明：
参数	描述
start	起始值，默认为0
stop	终止值（不包含）
step	步长，默认为1
dtype	返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。
'''
# 示例1  设置返回类型位 float 的数组
import numpy as np

x = np.arange(8, dtype = float)
print(x)   # [0. 1. 2. 3. 4. 5. 6. 7.]

# 示例1  设置设置了起始值、终止值及步长
y = np.arange(8,18,2)
print(y)   # [ 8 10 12 14 16]

[0. 1. 2. 3. 4. 5. 6. 7.]
[ 8 10 12 14 16]


In [10]:
# numpy.linspace
'''
numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
参数说明：
参数	     描述
start	     序列的起始值
stop	     序列的终止值，如果endpoint为true，该值包含于数列中
num	         要生成的等步长的样本数量，默认为50
endpoint	 该值为 true 时，数列中包含stop值，反之不包含，默认是True。
retstep	     如果为 True 时，生成的数组中会显示间距，反之不显示。
dtype	     ndarray 的数据类型
'''
# 示例 1    设置起始点为 1 ，终止点为 10，数列个数为 10

import numpy as np

a = np.linspace(1,10,10)
print(a)  # [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


# 示例 2    将 endpoint 设为 False，不包含终止值
a = np.linspace(8,18,5,endpoint = False,dtype = int)
print(a)  # [ 8 10 12 14 16]
# 如果将 endpoint 设为 true，则会包含 18。


# 示例 3    设置间距
a = np.linspace(8,18,5,retstep = True,dtype = int)
print(a)  # (array([ 8, 10, 13, 15, 18]), np.float64(2.5))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 8 10 12 14 16]
(array([ 8, 10, 13, 15, 18]), np.float64(2.5))


In [12]:
# numpy.logspace
'''
生成对数等距数组：在对数坐标轴上等间隔取点，线性轴上是指数分布。
公式：x_i = base^{start + i*step}
格式如下：

np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
base 参数意思是取对数的时候 log 的下标。
参数	    描述
start	    序列的起始值为：base ** start
stop	    序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
num	        要生成的等步长的样本数量，默认为50
endpoint    该值为 true 时，数列中中包含stop值，反之不包含，默认是True。
base	    对数 log 的底数。
dtype	    ndarray 的数据类型
'''
# 示例 1

import numpy as np

x = np.logspace(1,2,num = 10)
print(x)
'''
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
'''

# 示例 2     将对数的底数设置为 2
x = np.logspace(0,9,10,base = 2)
print(x)    # [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
