In [4]:
# 算术函数
'''
NumPy 算术函数包含简单的加减乘除: add()，subtract()，multiply() 和 divide()。
需要注意的是数组必须具有相同的形状或符合数组广播规则。
'''
import numpy as np
a = np.arange(9,dtype = float).reshape(3,3)
print('第一个数组为：\n',a)
'''
第一个数组为：
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
'''
b = np.array([10,10,10])
print('第二个数组为：\n',b)
'''
第二个数组为：
 [10 10 10]
'''
print('两个数组相加：\n',np.add(a,b))
'''
两个数组相加：
 [[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
'''
print('两个数组相减：\n',np.subtract(a,b))
'''
两个数组相减：
 [[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
'''
print('两个数组相乘：\n',np.multiply(a,b))
'''
两个数组相乘：
 [[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
'''
print('两个数组相除：\n',np.divide(a,b))
'''
两个数组相除：
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
'''


第一个数组为：
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
第二个数组为：
 [10 10 10]
两个数组相加：
 [[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
两个数组相减：
 [[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
两个数组相乘：
 [[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
两个数组相除：
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [5]:
# 线性代数

# numpy.dot()
'''
numpy.dot() 对于两个一维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为向量点积)；
对于二维数组，计算的是两个数组的矩阵乘积；
对于多维数组，它的通用计算公式如下，即结果数组中的每个元素都是：数组a的最后一维上的所有元素与数组b的倒数第二位上的所有元素的乘积和： dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])。

numpy.dot(a, b, out=None) 
参数说明：
a : ndarray 数组
b : ndarray 数组
out : ndarray, 可选，用来保存dot()的计算结果
'''
import numpy.matlib
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.dot(a,b))
'''
[[37 40]
 [85 92]]

计算式为：
[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]
'''

[[37 40]
 [85 92]]


'\n\n'

In [13]:
# 统计函数

# numpy.amin()
'''
用于计算数组中的元素沿指定轴的最小值。

numpy.amin(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
参数说明：
a: 输入的数组，可以是一个NumPy数组或类似数组的对象。
axis: 可选参数，用于指定在哪个轴上计算最小值。如果不提供此参数，则返回整个数组的最小值。可以是一个整数表示轴的索引，也可以是一个元组表示多个轴。
out: 可选参数，用于指定结果的存储位置。
keepdims: 可选参数，如果为True，将保持结果数组的维度数目与输入数组相同。如果为False（默认值），则会去除计算后维度为1的轴。
initial: 可选参数，用于指定一个初始值，然后在数组的元素上计算最小值。
where: 可选参数，一个布尔数组，用于指定仅考虑满足条件的元素。
'''
import numpy as np

a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print ('原始数组：\n',a)
'''
原始数组：
 [[3 7 5]
 [8 4 3]
 [2 4 9]]
'''
print ('调用 amin() 函数：\n',np.amin(a,1))
'''
调用 amin() 函数：
 [3 3 2]

axis=1：按行求最小值（横向，左右压缩）
'''
print ('二次调用 amin() 函数：\n',np.amin(a,0))
'''
二次调用 amin() 函数：
 [2 4 3]

axis=0：按列求最小值（纵向，上下压缩）
'''
print ('三次调用 amin() 函数：\n',np.amin(a))
'''
三次调用 amin() 函数：
 2

不写 axis：返回整个数组全局最小值
'''


# numpy.amax() 
'''
用于计算数组中的元素沿指定轴的最大值。

numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
参数说明：
a: 输入的数组，可以是一个NumPy数组或类似数组的对象。
axis: 可选参数，用于指定在哪个轴上计算最大值。如果不提供此参数，则返回整个数组的最大值。可以是一个整数表示轴的索引，也可以是一个元组表示多个轴。
out: 可选参数，用于指定结果的存储位置。
keepdims: 可选参数，如果为True，将保持结果数组的维度数目与输入数组相同。如果为False（默认值），则会去除计算后维度为1的轴。
initial: 可选参数，用于指定一个初始值，然后在数组的元素上计算最大值。
where: 可选参数，一个布尔数组，用于指定仅考虑满足条件的元素。
'''

print ('调用 amax() 函数：\n',np.amax(a,1))
'''
调用 amax() 函数：
[7 8 9]

axis=1：按行求最大值（横向，左右压缩）
'''
print ('二次调用 amax() 函数：\n',np.amax(a,0))
'''
二次调用 amax() 函数：
[8 7 9]

axis=0：按列求最大值（纵向，上下压缩）
'''
print ('三次调用 amax() 函数：\n',np.amax(a))
'''
三次调用 amax() 函数：
9

不写 axis：返回整个数组全局最大值
'''



# numpy.mean()
'''
numpy.mean() 函数返回数组中元素的算术平均值，如果提供了轴，则沿其计算。
算术平均值是沿轴的元素的总和除以元素的数量。

numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
参数说明：
a: 输入的数组，可以是一个 NumPy 数组或类似数组的对象。
axis: 可选参数，用于指定在哪个轴上计算平均值。如果不提供此参数，则计算整个数组的平均值。可以是一个整数表示轴的索引，也可以是一个元组表示多个轴。
dtype: 可选参数，用于指定输出的数据类型。如果不提供，则根据输入数据的类型选择合适的数据类型。
out: 可选参数，用于指定结果的存储位置。
keepdims: 可选参数，如果为True，将保持结果数组的维度数目与输入数组相同。如果为False（默认值），则会去除计算后维度为1的轴。
'''
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('原始数组：\n',a)
'''
原始数组：
 [[1 2 3]
 [3 4 5]
 [4 5 6]]
'''
b = np.mean(a)
print('调用mean()函数：\n',b)
'''
调用mean()函数：
 3.6666666666666665

无 axis：所有数字整体求平均
'''
c = np.mean(a,axis = 0)
print('沿轴 0 调用mean()函数：\n',c)
'''
沿轴 0 调用mean()函数：
 [2.66666667 3.66666667 4.66666667]

axis=0：竖着压，每一列算一个平均值
'''
d = np.mean(a,axis = 1)
print('沿轴 1 调用mean()函数：\n',c)
'''
沿轴 1 调用mean()函数：
 [2.66666667 3.66666667 4.66666667]

axis=1：横着压，每一行算一个平均值
'''



# 标准差
'''
标准差是一组数据平均值分散程度的一种度量。
标准差是方差的算术平方根。

标准差公式如下：
std = sqrt(mean((x - x.mean())**2))
'''
print(np.std([1,2,3,4]))   # 1.118033988749895
'''
数组是 [1，2，3，4]，则其平均值为 2.5。 
因此，差的平方是 [2.25,0.25,0.25,2.25]，并且再求其平均值的平方根除以 4;
即 sqrt(5/4) ，结果为 1.1180339887498949。
'''

原始数组：
 [[3 7 5]
 [8 4 3]
 [2 4 9]]
调用 amin() 函数：
 [3 3 2]
二次调用 amin() 函数：
 [2 4 3]
三次调用 amin() 函数：
 2
调用 amax() 函数：
 [7 8 9]
二次调用 amax() 函数：
 [8 7 9]
三次调用 amax() 函数：
 9
原始数组：
 [[1 2 3]
 [3 4 5]
 [4 5 6]]
调用mean()函数：
 3.6666666666666665
沿轴 0 调用mean()函数：
 [2.66666667 3.66666667 4.66666667]
沿轴 1 调用mean()函数：
 [2.66666667 3.66666667 4.66666667]
1.118033988749895
