In [9]:
# Numpy Ndarray 对象
'''
NumPy 的主要目标是齐次多维数组。它是 元素表（通常是数字），所有元素类型相同，并由 非负整数元组。在 NumPy 中，维度称为轴。
NumPy 最重要的一个特点是其 N 维数组对象 ndarray，它是一系列同类型数据的集合，以 0 下标为开始进行集合中元素的索引。
ndarray 对象是用于存放同类型元素的多维数组。
ndarray 中的每个元素在内存中都有相同存储大小的区域

ndarray 对象由计算机内存的连续一维部分组成，并结合索引模式，将每个元素映射到内存块中的一个位置。
内存块以行顺序(C样式)或列顺序(FORTRAN或MatLab风格，即前述的F样式)来保存元素。

ndarray 内部由以下内容组成：
一个指向数据（内存或内存映射文件中的一块数据）的指针。
数据类型或 dtype，描述在数组中的固定大小值的格子。
一个表示数组形状（shape）的元组，表示各维度大小的元组。
一个跨度元组（stride），其中的整数指的是为了前进到当前维度下一个元素需要"跨过"的字节数。

跨度可以是负数，这样会使数组在内存中后向移动，切片中 obj[::-1] 或 obj[:,::-1] 就是如此。
创建一个 ndarray 只需调用 NumPy 的 array 函数即可：
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
参数说明：
名称	描述
object	数组或嵌套的数列
dtype	数组元素的数据类型，可选
copy	对象是否需要复制，可选
order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
subok	默认返回一个与基类类型一致的数组
ndmin	指定生成数组的最小维度
'''
# 示例一  单维度
import numpy
a = numpy.array([1,2,3])
print(a)   # [1 2 3]

# 示例二  两个维度
b = numpy.array([[1,2],[3,4]])
print(b)   
'''
[[1 2]
 [3 4]]
.array([])  里面的 最外层的'[]'无论多少个维度不能少，固定格式，多少层'[]' 就有多少维度
'''
# 强制最小维度
c = numpy.array([1,2,3,4,5],ndmin = 2)
print(c)
'''
输出：
[[1 2 3 4 5]]

ndmin 作用：强制让生成的数组至少拥有指定维数，缺少几个维度会在外层补几个长度为 1 的轴；
不是修改数据元素数量，而是扩充「维度层数」。，所以这个例子里强制要求最小维度为2，缺少一个，就在最外层增加一层'[]'
'''

# type 参数
d  = numpy.array([1,2,3],dtype = complex)
print(d)
'''
输出：
[1.+0.j 2.+0.j 3.+0.j]

dtype=complex 指定数组存储复数类型复数数学标准格式：实部 + 虚部j，j 代表虚数单位 根号下 -1
传入的数字 1、2、3 都是纯实数，虚部为 0，因此 numpy 自动写成 数字+0.j。


[1 2 3]
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]
