In [2]:
# 广播（Broadcast)
'''
广播的规则:

让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。
输出数组的形状是输入数组形状的各个维度上的最大值。
如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来计算，否则出错。
当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。
简单理解：对两个数组，分别比较他们的每一个维度（若其中一个数组没有当前维度则忽略），满足：

数组拥有相同形状。
当前维度的值相等。
当前维度的值有一个是 1。
若条件不满足，抛出 "ValueError: frames are not aligned" 异常。
'''

# 如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的长度相同。
import numpy as np

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a*b
print(c)  # [ 10  40  90 160]


# 当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])   # a.shape(4,3)
b = np.array([0,1,2])     # b.shape(1,3)
print(a + b)
'''
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]

广播匹配校验（右对齐规则）
对齐后：
a：(4, 3)
b：(1, 3)
从后往前对比维度：
最后一维：3 == 3 
第一维：4 和 1（存在 1，可以广播拉伸）
输出最终形状：(4, 3)

b 形状 (1,3)，会纵向拉伸成 4 行，逻辑上等价下面矩阵：
plaintext
[[0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2]]

逐元素相加
每行对应相加：
第 0 行：[0,0,0] + [0,1,2] = [0, 1, 2]
第 1 行：[10,10,10] + [0,1,2] = [10, 11, 12]
第 2 行：[20,20,20] + [0,1,2] = [20, 21, 22]
第 3 行：[30,30,30] + [0,1,2] = [30, 31, 32]
'''

[ 10  40  90 160]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
