In [7]:
# NumPy 从已有的数组创建数组

# numpy.asarray
'''
numpy.asarray 类似 numpy.array，但 numpy.asarray 参数只有三个，比 numpy.array 少两个。

numpy.asarray(a, dtype = None, order = None)
参数说明：
参数	描述
a	任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，多维数组
dtype	数据类型，可选
order	可选，有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。
'''

# 示例 1   将列表转换为 ndarray 

import numpy as np

x = [1,2,3]
a = np.asarray(x)
print(a)  # [1 2 3]


# 示例 2   将元组转换为 ndarray
x = (1,2,3)
a = np.asarray(x)
print(a)  # [1 2 3]


# 示例 3   将元组列表转换为 ndarray
x =  [(1,2,3),(4,5,6)]
a = np.asarray(x)
print(a)
'''
[[1 2 3]
 [4 5 6]]
这里元组列表里的内容每组的长度必须一样，不能少一个或多一个，如 [(1,2,3),(4,5)] 就不可以
会报错：
ValueError: setting an array element with a sequence. 
The requested array has an inhomogeneous shape after 1 dimensions. 
The detected shape was (2,) + inhomogeneous part.
'''

# 示例4   设置了 dtype
x = (1,2,3)
a = np.asarray(x,dtype = float)
print(a)  # [1. 2. 3.]

[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]]
[1. 2. 3.]


In [11]:
# numpy.frombuffer
'''
numpy.frombuffer 用于实现动态数组。
numpy.frombuffer 接受 buffer 输入参数，以流的形式读入转化成 ndarray 对象。
Buffer（缓冲区）= 一块连续的内存空间，专门用来存放原始二进制字节数据。
计算机底层所有文件、网络、内存读写本质都是0/1 二进制字节，buffer 就是承载这些原始字节的容器。

numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
注意：buffer 是字符串的时候，Python3 默认 str 是 Unicode 类型，所以要转成 bytestring 在原 str 前加上 b。
参数说明：
参数	描述
buffer	可以是任意对象，会以流的形式读入。
dtype	返回数组的数据类型，可选
count	读取的数据数量，默认为-1，读取所有数据。
offset	读取的起始位置，默认为0。
'''
# 示例

import numpy as np

x = b'hello world'
a = np.frombuffer(x,dtype = 'S1')
print(a)   # [b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
'''
输出：
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']

'hello world'，前必须加 b 将其字节化
不然无法流入 buffer,dtype

只要调用 np.frombuffer
输入必须是 bytes（带 b 字符串 /str.encode ()）；
dtype 按需选：S1/S2/uint8/float32 都行，S1 只是单字节字符场景专用。

普通创建字符数组（np.array）
不用 b，普通 str 直接用；
dtype 用 U1 而非 S1。
'''

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']


'\n\n'

In [15]:
# numpy.fromiter
'''
numpy.fromiter 方法从可迭代对象（生成器、列表、元组、迭代器）中建立 ndarray 对象，返回一维数组。

numpy.fromiter(iterable, dtype, count=-1)
参数	描述
iterable	可迭代对象
dtype	返回数组的数据类型
count	读取的数据数量，默认为-1，读取所有数据
'''
import numpy as np

lis = range(8)
x = np.fromiter(lis,dtype = float)
print(x)   # [0. 1. 2. 3. 4. 5. 6. 7.]
'''
源码内部会自动调用 iter() 把输入转为迭代器

iter () 什么时候必须手动在 np.fromiter（） 前写？
需要提前手动用 next() 消耗部分数据；
多层嵌套迭代、自定义生成器场景；
单纯给 fromiter 传参，不需要手动 iter()。
'''

[0. 1. 2. 3. 4. 5. 6. 7.]
