In [11]:
# 数组操作

# 修改数组形状
'''
函数	描述
reshape	不改变数据的条件下修改形状
flat	数组元素迭代器
flatten	返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
ravel	返回展开数组
'''
# numpy.reshape
'''
numpy.reshape 函数可以在不改变数据的条件下修改形状，格式如下：

numpy.reshape(arr, newshape, order='C')
arr：要修改形状的数组
newshape：整数或者整数数组，新的形状应当兼容原有形状
order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。
'''
import numpy as np

a = np.arange(8)
print('原始数组为：\n',a)
'''
原始数组为：
 [0 1 2 3 4 5 6 7]
'''
b = a.reshape(4,2)
print('修改后数组为：\n',b)
'''
修改后数组为：
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
'''


# numpy.ndarray.flat
'''
ndarray.flat 是 NumPy 数组的一维迭代器属性（不是函数，是属性），将任意维度数组展平为一维序列，逐个遍历所有元素。
返回类型：numpy.flatiter 迭代对象。
原地映射：修改迭代器元素会直接修改原数组（共享内存）
'''
a = np.arange(9).reshape(3,3)
print('原始数组为：')
for x in a:
    print(x)
'''
原始数组为：
[0 1 2]
[3 4 5]
[6 7 8]
'''
#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print('迭代后数组为：')
for x in a.flat:
    print(x,end = '  ')
'''
迭代后数组为：
0  1  2  3  4  5  6  7  8  
'''

print('\n')

# numpy.ndarray.flatten
'''
numpy.ndarray.flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组，格式如下：

ndarray.flatten(order='C')
参数说明：
order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。
'''
a = np.arange(8).reshape(2,4)
print('原始数组为：\n',a)
'''
原始数组为：
 [[0 1 2 3]
 [4 5 6 7]]
'''
b = a.flatten()
print('展开后的数组：\n',b)
'''
展开后的数组：
 [0 1 2 3 4 5 6 7]
'''
c = a.flatten(order = 'F')
print('以 F 顺序展开的数组：\n',c)
'''
以 F 顺序展开的数组：
 [0 4 1 5 2 6 3 7]
'''


# numpy.ravel
'''
numpy.ravel() 展平的数组元素，顺序通常是"C风格"，返回的是数组视图（view，有点类似 C/C++引用reference的意味），修改会影响原始数组。

numpy.ravel(a, order='C')
参数说明：
order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。
'''
a = np.arange(8).reshape(2,4)
print('原始数组为：\n',a)
'''
原始数组为：
 [[0 1 2 3]
 [4 5 6 7]]
'''
b = a.ravel()
print('调用 ravel 函数后为：\n',b)
'''
调用 ravel 函数后为：
 [0 1 2 3 4 5 6 7]
'''
c = a.ravel(order = 'F')
print('以 F 顺序调用 ravel 函数的数组：\n',c)
'''
以 F 顺序调用 ravel 函数的数组：
 [0 4 1 5 2 6 3 7]
'''

原始数组为：
 [0 1 2 3 4 5 6 7]
修改后数组为：
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
原始数组为：
[0 1 2]
[3 4 5]
[6 7 8]
迭代后数组为：
0  1  2  3  4  5  6  7  8  

原始数组为：
 [[0 1 2 3]
 [4 5 6 7]]
展开后的数组：
 [0 1 2 3 4 5 6 7]
以 F 顺序展开的数组：
 [0 4 1 5 2 6 3 7]
原始数组为：
 [[0 1 2 3]
 [4 5 6 7]]
调用 ravel 函数后为：
 [0 1 2 3 4 5 6 7]
以 F 顺序调用 ravel 函数的数组：
 [0 4 1 5 2 6 3 7]


In [21]:
# 翻转数组
'''
函数	    描述
transpose	对换数组的维度
ndarray.T	和 self.transpose() 相同
rollaxis	向后滚动指定的轴
swapaxes	对换数组的两个轴
'''
# numpy.transpose
'''
numpy.transpose 函数用于对换数组的维度，格式如下：

numpy.transpose(arr, axes)
参数说明:
arr：要操作的数组
axes：整数列表，对应维度，通常所有维度都会对换。
'''

import numpy as np

a = np.arange(12).reshape(3,4)
print('原数组：\n',a)
'''
原数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
'''
b = np.transpose(a)
print('兑换后的数组：\n',b)
'''
兑换后的数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
'''


# numpy.ndarray.T 类似 numpy.transpose
a = np.arange(12).reshape(3,4)
print('原数组：\n',a)
'''
原数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
'''
b = a.T
print('转置后的数组：\n',b)
'''
兑换后的数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
'''


# numpy.rollaxis
'''
numpy.rollaxis 函数向后滚动特定的轴到一个特定位置，格式如下：

numpy.rollaxis(arr, axis, start)
参数说明：
arr：数组
axis：要向后滚动的轴，其它轴的相对位置不会改变
start：默认为零，表示完整的滚动。会滚动到特定位置。
'''

'''
3 维 a(H,W,C)
三层含义 a[外层块, 行, 列]
数组 img.shape = (100, 200, 3)
轴 0=H 高度 (100 行)，轴 1=W 宽度 (200 列)，轴 2=C 通道 (3)
'''

a = np.arange(8).reshape(2,2,2)
print('原数组：\n',a)
'''
原数组：
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
'''
print('获取其中 6 的位置：',np.where(a==6))  # 获取其中 6 的位置： (array([1]), array([1]), array([0]))

# 将轴 2 滚动到轴 0（宽度到深度）
b = np.rollaxis(a,2,0)
print('获取 rollaxis 后 6 的位置：',np.where(b==6))  # 获取 rollaxis 后 6 的位置： (array([0]), array([1]), array([1]))
# 最后一个 0 移动到最前面

# 将轴 2 滚动到轴 1：（宽度到高度）
c = np.rollaxis(a,2,1)
print('获取再次 rollaxis 后 6 的位置：',np.where(c==6))  # 获取再次 rollaxis 后 6 的位置： (array([1]), array([0]), array([1]))



# numpy.swapaxes
'''
numpy.swapaxes 函数用于交换数组的两个轴，格式如下：

numpy.swapaxes(arr, axis1, axis2)
arr：输入的数组
axis1：对应第一个轴的整数
axis2：对应第二个轴的整数
'''
a = np.arange(8).reshape(2,2,2)
print('原数组：\n',a)
'''
原数组：
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
'''

# 交换轴 0 到轴 2
b = np.swapaxes(a,2,0)
print('swapaxis 后的数组：\n',b)
'''
swapaxis 后的数组：
 [[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]

原来的 列 变成了 块
'''

原数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
兑换后的数组：
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
原数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转置后的数组：
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
原数组：
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
获取其中 6 的位置： (array([1]), array([1]), array([0]))
获取 rollaxis 后 6 的位置： (array([0]), array([1]), array([1]))
获取再次 rollaxis 后 6 的位置： (array([1]), array([0]), array([1]))
原数组：
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
swapaxis 后的数组：
 [[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [38]:
# 修改数组维度
'''
维度	描述
broadcast	产生模仿广播的对象
broadcast_to	将数组广播到新形状
expand_dims	扩展数组的形状
squeeze	从数组的形状中删除一维条目
'''

# numpy.expand_dims
'''
numpy.expand_dims 函数通过在指定位置插入新的轴来扩展数组形状，函数格式如下:

numpy.expand_dims(arr, axis)
参数说明：
arr：输入数组
axis：新轴插入的位置
'''
import numpy as np

x = np.array([[1,2],[3,4]])
print('原数组：\n',x)
'''
原数组：
 [[1 2]
 [3 4]]
'''
print(x.shape)   # (2, 2)
'''
x.shape = (2, 2)，两根轴：
轴 0：行数 2；轴 1：列数 2
'''

y = np.expand_dims(x,axis = 0)
print(' y 数组：\n',y)
'''
y 数组：
 [[[1 2]
  [3 4]]]
视觉理解：把整个 2×2 矩阵整体包一层外壳
'''
print(y.shape)   # (1, 2, 2)
'''
在最前面（axis=0）插入长度为 1 的新轴
原始轴序列：[0, 1]
插入新轴在 0 号位置 → 新轴顺序 [新轴, 原0轴, 原1轴]
新轴长度 = 1，原两轴保持 2、2
最终 shape：(1, 2, 2)
'''

# 在位置 1 插入轴
z = np.expand_dims(x,axis = 1)
print(' z 数组：\n',z)
'''
z 数组：
 [[[1 2]]

 [[3 4]]]
视觉理解：矩阵每一行单独包一层 []
'''
print(f"x.ndim 为：{x.ndim} 和 z.ndim 为：{z.ndim}")  # x.ndim 为：2 和 z.ndim 为：3
print(f"x.shape 为：{x.shape} 和 z.shape 为：{z.shape}")  # x.shape 为：(2, 2) 和 z.shape 为：(2, 1, 2)
'''
z:
在中间（axis=1）插入长度为 1 的新轴
原始轴序列：[0, 1]
插入新轴在 1 号位置 → 新轴顺序 [原0轴, 新轴, 原1轴]
原轴 0=2，新轴 = 1，原轴 1=2
最终 shape：(2, 1, 2)
'''


# numpy.squeeze
'''
numpy.squeeze 函数从给定数组的形状中删除一维的条目，函数格式如下：

numpy.squeeze(arr, axis)
参数说明：
arr：输入数组
axis：整数或整数元组，用于选择形状中一维条目的子集
'''
x = np.arange(9).reshape(1,3,3)
print('数组 x ：\n',x)
'''
数组 x ：
 [[[0 1 2]
  [3 4 5]
  [6 7 8]]]
'''
y = np.squeeze(x)
print('数组 y ：\n',y)
'''
数组 y ：
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
'''
print(f"数组 x 的形状:{x.shape} 和 数组 y 的形状：{y.shape} ")   # 数组 x 的形状:(1, 3, 3) 和 数组 y 的形状：(3, 3) 


原数组：
 [[1 2]
 [3 4]]
(2, 2)
 y 数组：
 [[[1 2]
  [3 4]]]
(1, 2, 2)
 z 数组：
 [[[1 2]]

 [[3 4]]]
x.ndim 为：2 和 z.ndim 为：3
x.shape 为：(2, 2) 和 z.shape 为：(2, 1, 2)
数组 x ：
 [[[0 1 2]
  [3 4 5]
  [6 7 8]]]
数组 y ：
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
数组 x 的形状:(1, 3, 3) 和 数组 y 的形状：(3, 3) 
数组 z ：
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
