In [5]:
# Sklearn 数据预处理
'''
在进行机器学习建模时，数据预处理是至关重要的一步，它帮助我们清洗和转换原始数据，以便为机器学习模型提供最佳的输入。
数据预处理涉及多个步骤，包括处理缺失值、数据转换、标准化、编码等。
合适的预处理不仅能提高模型的准确性，还能帮助模型更好地泛化。
'''



# 1、处理缺失值
'''
缺失值是指在数据集中某些特征的值缺失。
机器学习算法通常无法直接处理缺失值，因此我们需要对缺失值进行处理。

检查缺失值
首先，检查数据集中是否有缺失值。
通常可以使用 pandas 来查看数据集中的缺失值
df.isnull() 等函数

填充缺失值
对于缺失值的处理，最常用的方法是填充。
常见的填充策略包括：
填充均值（Mean）：适用于数值型数据。
填充中位数（Median）：对于含有离群值的数据集，使用中位数可能更有效。
填充最频繁值（Mode）：适用于类别型数据。

删除缺失值
如果缺失值的数量较少，并且删除这些数据不会显著影响分析结果，另一种选择是直接删除缺失值。
df_cleaned = df.dropna()  # 删除包含缺失值的行
'''
# 示例   SimpleImputer 实现缺失值填充

from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

# 对于数值型数据，使用均值填充
imputer = SimpleImputer(strategy = 'most_frequent')   # 可选：'mean', 'median', 'most_frequent'

df = pd.DataFrame({
    "age": [16, np.nan, 20, 22],
    "weather": ["sunny", np.nan, "today", "rain"]
})

df_imputed = imputer.fit_transform(df)  # 填充缺失值
'''
strategy 规则:
数值列：缺失值可以用 mean均值 / median中位数填充
字符串、分类文本列（sunny、rain、cloud）：不能求平均值，只能使用 most_frequent（众数，出现最多的值）填充

文本类别填充完之后依旧是字符串，模型无法直接训练，需要编码：
OneHotEncoder：独热编码
LabelEncoder：标签编码
训练集执行 fit，测试集只允许调用 transform，杜绝数据泄露
可以用 df.dtypes 查看字段类型，object 代表字符串列
'''

In [8]:
# 2、数据缩放
'''
机器学习算法对数据的尺度敏感，因此需要对数据进行缩放，使得特征具有相同的尺度。
常见的缩放方法有：

标准化（Standardization）：将数据转换为均值为0、标准差为1的分布。适用于大多数机器学习算法。
对于距离度量（如 K 最近邻、支持向量机等）非常重要，因为特征的尺度不一致可能导致某些特征对模型的影响过大。标准化能确保每个特征对模型有相同的贡献。

归一化（Normalization）：将数据缩放到指定范围（通常是 [0, 1]）。
有些算法（如神经网络、梯度下降优化算法等）对输入数据的范围非常敏感，归一化有助于加速收敛。
'''


# 3、类别变量编码
'''
机器学习模型通常无法直接处理字符串类型的类别变量，因此需要将类别变量转化为数值型数据。
常见的编码方法有：

标签编码
标签编码将每个类别映射到一个唯一的整数。
适用于类别之间有顺序关系的情况（例如，低、中、高）。
'''
# 示例

from sklearn.preprocessing import LabelEncoder

# 实例化
label_encoder = LabelEncoder()

y = np.array(["sunny", "rain", "sunny", "cloud", "rain"])
y_encoded = label_encoder.fit_transform(y)   # 将类别变量转换为整数


# 独热编码
'''
独热编码将每个类别转换为一个二进制的向量，适用于类别之间没有顺序关系的情况（例如，颜色、国家等）。
OneHotEncoder 可以将类别变量转化为独热编码。

在 pandas 中，也可以使用 get_dummies() 函数进行独热编码：
X_encoded = pd.get_dummies(X)
'''
# 示例
from sklearn.preprocessing import OneHotEncoder
import numpy as np

encoder = OneHotEncoder(sparse_output = False)  # sparse_output=False 返回一个密集矩阵

# 二维特征，天气特征列
X = np.array([["sunny"],["rain"],["sunny"],["cloud"]])
X_encoded = encoder.fit_transform(X)# 将类别变量转换为独热编码
print(X_encoded)
'''
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
'''

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
# 4、特征选择
'''
特征选择是通过选择最重要的特征来提高模型的性能，并减少计算成本。
常见的特征选择方法包括：
基于模型的特征选择
使用一些机器学习模型（如决策树或随机森林）来评估特征的重要性，从而进行特征选择。
'''
# 示例
from sklearn.ensemble import RandomForestClassifier   # 导入随机森林模块
from sklearn.tree import DecisionTreeClassifier       # 导入决策树模块

# 训练一个随机森林模型
clf = RandomForestClassifier()
clf.fit(X_train,y_train)

# 训练决策树
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

# 获取特征重要性
print(clf.feature_importance_)   # .feature_importance_ 特征重要性数组，一维数组，总和等于 1

# 预测、输出准确率
print(clf.score(X_test, y_test))
'''
ensemble：集成算法模块；随机森林属于Bagging‑集成学习，由大量决策树投票得出最终结果
tree 属于 scikit‑learn 的树算法子模块，专门存放所有和决策树相关的类、函数

clf = RandomForestClassifier(
    n_estimators=100,        # 决策树的总数量，默认100
    max_depth=None,           # 单棵树最大深度，None代表不限制深度
    random_state=42,          # 固定随机种子，保证结果可以复现
    n_jobs=-1,                 # 使用电脑全部CPU并行训练
    min_samples_split=2
)

clf = DecisionTreeClassifier(
    max_depth=4,          # 树最大深度，限制深度避免过拟合
    random_state=42,      # 固定随机种子，结果复现
    criterion="gini"      # gini基尼系数 / entropy信息熵，作为分裂标准
)

feature_importance_ 数值越大，代表该特征对判断分类结果贡献越高
'''


# 递归特征消除（Recursive Feature Elimination，RFE）
'''
RFE 是一种通过递归的方式，逐步删除最不重要的特征，从而选择最优特征的方法。
RFE 可以帮助我们自动选择重要特征。
'''
from sklearn.feature_selection import RFE

# 使用线性模型进行递归特征消除
rfe = RFE(clf, n_features_to_select = 3)  # 保留 3 个最重要的特征
X_rfe = rfe.fit_transform(X_train, y_train)
'''
rfe = RFE(
    estimator=clf,               # 基础模型(决策树、随机森林、逻辑回归，需要可以输出特征权重)
    n_features_to_select=3,      # 最终保留多少个特征
    step=1,                       # 每一轮递归删除几个特征，默认一次剔除1个
    verbose=0,                    # 日志打印等级
    importance_getter="auto"     # 获取特征重要性的方式，auto自动识别
)

常用属性
rfe.support_         # 布尔数组，True=该特征被选中
rfe.ranking_         # 特征排名，1 代表选中

fit：不断训练、淘汰不重要特征
transform：截取筛选后的特征
测试集禁止 fit，防止数据泄露
'''

In [ ]:
# 5、特征工程
'''
特征工程是通过对现有特征进行处理、组合或构造新的特征，以提高模型的表现。
特征工程的常见方式包括：
特征组合：将两个或更多的特征组合成一个新特征。
特征转换：对特征进行对数变换、平方根变换等，以解决数据的非线性问题。
特征创建：根据现有数据创建新的特征，例如从时间戳中提取出日期、月份、星期等。

# 例如，将两个数值型特征组合成一个新特征
df['new_feature'] = df['feature1'] * df['feature2']
'''



# 6、特征提取
'''
特征提取旨在从原始特征中提取出新的、更具表达力的特征。
常见的特征提取方法包括: 主成分分析（PCA） 和 线性判别分析（LDA）。

主成分分析（PCA）
PCA 是一种常用的降维技术，它通过线性变换将数据从高维空间映射到低维空间，使得新特征（主成分）尽可能保留数据的方差。
PCA 特别适用于特征数量过多的情况，可以有效降低计算复杂度。

PCA 主要用于两种场景：
降维：当特征过多时，使用 PCA 降维可以减少计算成本，同时保留数据的主要信息。
可视化：将高维数据映射到 2D 或 3D 空间，帮助我们可视化数据结构。
'''
# 示例
from sklearn.decomposition import PCA

# 假设 X 是特征矩阵
pca = PCA(n_components = 2)  # 降维到 2 个主成分
X_pca = pca.fit_transform(X)
'''
pca = PCA(
    n_components=2,     # 保留主成分数量；也可以填小数0.95代表保留95%信息
    random_state=42     # 最后保留 2 维新特征（常用于二维可视化）
)

fit(X)：计算数据集的协方差矩阵、特征向量，找到主成分方向；只读取特征，PCA 属于无监督，不需要标签 y
transform(X)：把原始数据投影到新坐标轴，完成降维
fit_transform = 拟合 + 转换
'''

# 线性判别分析（LDA）
'''
LDA 是一种监督学习的降维方法，它旨在找到一个线性组合，使得不同类别之间的距离最大化，类别内的距离最小化。
LDA 通常用于分类任务中。
'''
# 示例
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 假设 X 是特征矩阵，y 是目标变量
lda = LinearDiscriminantAnalysis(n_componants = 2)  # 降维到 2 个线性判别组件
X_lda = lda.fit_transform(X, y)   # 
'''
lda = LinearDiscriminantAnalysis(
    n_components=2,   # 降维之后最终保留多少个特征维度
    solver="svd"   # 求解器，核心参数；三种可选模式：svd、lsqr、eigen
)
solver="svd"（默认）
奇异值分解；最常用，不需要计算协方差矩阵，适合特征数量很多、数据量大，稳定性最好。
solver="lsqr"
最小二乘法；适合样本数量小于特征数、带有正则化。
solver="eigen"
特征值分解；适合类别很少、数据简单的场景。
'''

In [ ]:
# 7、处理不平衡数据
'''
在分类问题中，如果数据集的各类别样本数量差异较大，可能会导致模型偏向预测多数类，从而影响模型的性能。
常见的处理方法包括：

上采样（Over-sampling）
通过增加少数类样本的数量，使得数据集更加平衡。
常见的方法是使用 SMOTE（Synthetic Minority Over-sampling Technique） 算法。
'''
# 示例
from imlearn.over_sampling import SMOTE

smote = SMOTE()
X_resampled,y_resampled = smote.fit_resample(X_train, y_train)
'''
imblearn：专门处理不平衡数据集的第三方库，不属于 sklearn
over_sampling：过采样模块；SMOTE 是最经典的上采样算法
作用：当某一类样本数量很少（少数类），人工生成新的少数类样本，让各类样本数量持平

smote = SMOTE(
    sampling_strategy="auto",   # 采样策略；auto：少数类扩充至和多数类样本数目一致
    k_neighbors=5,              # 近邻数量，默认5‑NN
    random_state=42
)

fit：学习少数样本分布、邻近点
resample：插值生成新样本，重采样平衡数据集
fit_resample() = 拟合 + 重采样，一次性返回平衡后的特征、标签

SMOTE 只对训练集做重采样；测试集绝对不能采样。
测试集必须保留原始真实分布，用来真实评估模型。
'''

# 下采样（Under-sampling）
# 通过减少多数类样本的数量，使得数据集更加平衡。
from imlearn.under_sampling import RandomUnderSampler

undersampler = RandomUnderSampler()
X_resampled, y_resampled = undersampler.fit_resample(X_train, y_train)
'''
under_sampling：欠采样（下采样）模块
随机下采样原理：随机删掉样本数量多的多数类样本，让各类样本数目持平

undersampler = RandomUnderSampler(
    sampling_strategy="auto",  # auto：多数类样本删减到和少数类样本数量相等
    random_state=42,
    replacement=False   # False：无放回随机挑选；True：有放回抽样，允许重复选取同一个样本
)

下采样只能够作用于训练集，测试集必须保持原始样本分布，绝对不能重采样
'''